### ISSUE TITLE
pkg-config error while trying to npm install -g storj

### ISSUE THREAD

**Issue by tdude08** [Storj/node-libstorj#58] opened 2018-02-02 19:13 UTC
I tried to install storj globally from the getting started documentation using
```bash
npm install -g storj
````
but I get this error
'pkg-config' is not recognized as an internal or external command. 

Am I missing anything. Thanks.

System/tools details:
OS: windows 10 x64
node: v8.9.3
npm: v5.6.0

**Comment by braydonf** [comment] 2018-02-02 19:53
Windows isn't yet supported.

Duplicate of https://github.com/Storj/node-libstorj/issues/43.

**Closed by braydonf** 2018-02-02 19:53 UTC

**Comment by tdude08** [comment] 2018-07-21 16:09
Ok, thanks, I didn't know that.
