### ISSUE TITLE
Support installation on windows

### ISSUE THREAD

**Issue by braydonf** [storj/node-libstorj#43] opened 2017-10-04 17:54 UTC
There is most likely going to be an issue on windows when installing, as the downloaded release is a zip file instead of a tarball, and we'll need to switch to use `zip` command, at https://github.com/Storj/node-libstorj/blob/master/download.js#L47

Would cygwin be used here, and bash scripts would work?

**Comment by graphenepay** [comment] 2017-10-15 10:42
Issue confirmed on Windows setup.

**Comment by seekerlee** [comment] 2018-01-15 16:09
multiple issues with windows.

- download/unzip not working
- not compiling because some linux-only functions being used (access function) and some other.
- not linking (it seems nettle and some other link fails)

I will work on this recently. Just FYI what I found now.

**Comment by dittops** [comment] 2018-01-24 03:20
Do we have a solution for this issue?

**Comment by tolstenko** [comment] 2018-02-08 15:25
I got same error using MSYS2 enviroment.

Running 
`npm install github:storj/node-libstorj --save`
On Windows 10
```
npm ERR! argv "C:\\msys64\\mingw64\\bin\\node.exe" "C:\\msys64\\mingw64\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "github:storj/node-libstorj" "--save"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! storj@5.1.0 preinstall: `node ./download.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the storj@5.1.0 preinstall script 'node ./download.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the storj package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs storj
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls storj
npm ERR! There is likely additional logging output above.
```

**Comment by hunterInt** [comment] 2018-03-25 17:04
I'm getting the same error on windows 64bit: (is there any solution for this yet? Or when will Storj be stable for windows?)

storj@5.1.0 preinstall C:\Users\hunter\Documents\vid\node_modules\storj
> node ./download.js
Unable to download libstorj for platform: win32 and arch: x64
npm WARN vid@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storj@5.1.0 preinstall: `node ./download.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the storj@5.1.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\hunter\AppData\Roaming\npm-cache\_logs\2018-03-24T20_59_10_765Z-debug.log

**Comment by hAbd0u** [comment] 2018-05-30 03:42
I have the same error too.

**Comment by RichardLitt** [comment] 2018-10-30 10:51
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

**Closed by RichardLitt** 2018-10-30 10:51 UTC
